development:
  secret_key_base: <%= Settings['app.secret_key_base'] %>

test:
  secret_key_base: <%= Settings['app.secret_key_base'] %>

production:
  secret_key_base: <%= Settings['app.secret_key_base'] %>
